import "./globals.css"
import "@radix-ui/themes/styles.css"

import { Theme } from "@radix-ui/themes"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { notFound } from "next/navigation"

import { type LayoutParams } from "@/types/layout-params"
import { isValidLocale } from "@/utils/is-valid-locale"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

type LocaleLayoutParams = LayoutParams<{
    locale: string
}>

export default function LocaleLayout({ children, params }: LocaleLayoutParams) {
    if (!isValidLocale(params.locale)) return notFound()

    return (
        <html lang={params.locale}>
            <body className={inter.className}>
                <Theme>{children}</Theme>
            </body>
        </html>
    )
}
